version: '2'

services:
  postgresql:
    image: postgres:15
    ports:
      - 5437:5432
    volumes:
      - ./docker_data/postgres:/data/postgres
    container_name: labeled-addresses-postgresql
    environment:
      POSTGRES_USER: labeled-addresses
      POSTGRES_PASSWORD: labeled-addresses
      PGDATA: /data/postgres
